DoAn_ThiTracNghiem_Complete/Areas/Admin/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn_ThiTracNghiem_Complete.Common;
using Model.Dao;
using Model.EF;
using DoAn_ThiTracNghiem_Complete.Areas.Admin.Code;
using System.Threading.Tasks;
using System.IO;
using System.Web.Hosting;
using System.Text.RegularExpressions;
using System.Runtime.Remoting.Messaging;

namespace DoAn_ThiTracNghiem_Complete.Areas.Admin.Controllers
{
    public class SubjectController : BaseController
    {
        // GET: Admin/Subject
        //phần về thông tin môn :D
        public ActionResult Index()
        {
            var dao = new AdminDao();
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            dao.UpdateLastLogin(session.id_admin);
            dao.UpdateLastSeen("Quản lý môn học", "Admin/Subject/", session.id_admin);
            var dap1 = new SubjectDao();
            var model = dap1.LissAll();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var dao = new AdminDao();
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            dao.UpdateLastLogin(session.id_admin);
            dao.UpdateLastSeen("Thêm môn học", "Admin/Subject/Create", session.id_admin);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Subject collection)
        {
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            if (ModelState.IsValid)
            {

                var dao = new SubjectDao();


                int id = dao.Insert(collection);
                if (id > 0)
                {
                    //để thông báo thêm thành công
                    SetNotice("Hệ thống đã thêm thành công.", "success");
                    return RedirectToAction("Create");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm môn học không thành công.");
                }

            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dao = new AdminDao();
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;


            var dao1 = new SubjectDao().ViewDetail(id);
            if (dao1 == null) return View("Error");
            else
            {
                dao.UpdateLastLogin(session.id_admin);
                dao.UpdateLastSeen("Sửa thông tin của môn " + dao1.subject_name, "/Admin/Subject/Edit" + dao1.id_subject, session.id_admin);

                return View(dao1);
            }
        }
        [HttpPost]
        public ActionResult Edit(Model.EF.Subject collection)
        {

            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            var dao = new SubjectDao();

            var id = dao.Update(collection);
            if (id)
            {
                SetNotice("Hệ thống đã sửa thành công môn " + collection.subject_name + ".", "success");
                return RedirectToAction("Index");
            }
            else
            {
                SetNotice("Có lỗi xảy ra!!", "danger");
                ModelState.AddModelError("", "Cập nhật thông tin môn không thành công.");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            var result = new SubjectDao().Delete(id);
            if (result == true)
            {

            }
            return RedirectToAction("Index");
        }

        //phần về thông tin các chuyên đề của môn
        [HttpGet]
        public ActionResult Detail(int id)
        {
            var dao = new AdminDao();
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;


            var dao2 = new SubjectDao().ViewDetail(id);
            var dao1 = new ThematicDao().ListThematicInSubject(id);
            if (dao2 == null) return View("Error");
            else
            {
                dao.UpdateLastLogin(session.id_admin);
                dao.UpdateLastSeen("Xem thông tin của môn học " + dao2.subject_name, "/Admin/Subject/Detail" + dao2.id_subject, session.id_admin);
                TempData["subject_name"] = dao2.subject_name;
                TempData["id_subject"] = id;
                return View(dao1);
            }
        }
        [HttpGet]
        public ActionResult CThematic(int id)
        {
            var dao = new AdminDao();
            var dao2 = new SubjectDao().ViewDetail(id);
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            dao.UpdateLastLogin(session.id_admin);
            dao.UpdateLastSeen("Thêm chuyên đề cho môn " + dao2.subject_name, "Admin/Subject/CThematic/" + dao2.id_subject, session.id_admin);
            TempData["subject_name"] = dao2.subject_name;
            TempData["id_subject"] = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CThematic(Thematic collection)
        {
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            if (ModelState.IsValid)
            {

                var dao = new ThematicDao();


                int id = dao.Insert(collection);
                if (id > 0)
                {
                    //để thông báo thêm thành công
                    SetNotice("Hệ thống đã thêm thành công.", "success");
                    return RedirectToAction("Detail", new { id = collection.id_subject });
                }
                else
                {
                    var dao2 = new SubjectDao().ViewDetail(collection.id_subject);
                    TempData["subject_name"] = dao2.subject_name;
                    TempData["id_subject"] = collection.id_subject;
                    ModelState.AddModelError("", "Thêm chuyên đề không thành công.");
                }

            }
            var dao3 = new SubjectDao().ViewDetail(collection.id_subject);
            TempData["subject_name"] = dao3.subject_name;
            TempData["id_subject"] = collection.id_subject;
            return View();
        }

        [HttpGet]
        public ActionResult EThematic(int id)
        {
            var dao = new AdminDao();
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;


            var dao1 = new ThematicDao().ViewDetail(id);
            if (dao1 == null) return View("Error");
            else
            {
                var dao2 = new SubjectDao().ViewDetail(dao1.id_subject);
                dao.UpdateLastLogin(session.id_admin);
                dao.UpdateLastSeen("Sửa tên chuyên đề của môn " + dao2.subject_name, "/Admin/Subject/EThematic/" + dao2.id_subject, session.id_admin);
                TempData["subject_name"] = dao2.subject_name;
                TempData["id_subject"] = dao2.id_subject;
                return View(dao1);
            }
        }
        [HttpPost]
        public ActionResult EThematic(Model.EF.Thematic collection)
        {
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;


            var dao = new ThematicDao();

            var id = dao.Update(collection);
            if (id)
            {
                SetNotice("Hệ thống đã sửa thành công chuyên đề " + collection.thematic_name + ".", "success");
                return RedirectToAction("Detail", new { id = collection.id_subject });
            }
            else
            {
                var dao2 = new SubjectDao().ViewDetail(collection.id_subject);
                TempData["subject_name"] = dao2.subject_name;
                TempData["id_subject"] = collection.id_subject;
                SetNotice("Có lỗi xảy ra!!", "danger");
                ModelState.AddModelError("", "Cập nhật thông tin chuyên đề không thành công.");
            }
            var dao3 = new SubjectDao().ViewDetail(collection.id_subject);
            TempData["subject_name"] = dao3.subject_name;
            TempData["id_subject"] = collection.id_subject;
            return View();

        }


        public ActionResult DThematic(int id)
        {
            var session = (AdminLogin)Session[CommonConstants.USER_SESSION];
            if (session.id_permission == 2)
                return View("Error");
            ViewBag.AdminName = session.name;

            var result = new ThematicDao().Delete(id);
            if (result == true)
            {

            }
            return RedirectToAction("Index");
        }

        // phần các câu hỏi của môn
        [HttpGet]

DoAn_ThiTracNghiem_Complete/Areas/Admin/Views/Subject/QCreate.cshtml
@model Model.EF.Question


@{
    ViewBag.Title = "Thêm ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section css
    {

    <!-- Wait Me Css -->
    <link href="/Assets/admin/plugins/waitme/waitMe.css" rel="stylesheet" />
    <!-- Bootstrap Select Css -->
    <link href="/Assets/admin/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="/Assets/admin/css/style.css" rel="stylesheet">

}
@section title
{
    <title>Thêm câu hỏi cho môn @TempData["subject_name"]</title>
}

<div class="block-header">

</div>
<!-- ADD FORM -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    THÊM CÂU HỎI CHO MÔN @TempData["subject_name"].ToString().ToUpper()
                </h2>
            </div>
            <div class="body">
                @using (Html.BeginForm("QCreate", "Subject", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <input data-val="true" id="id_subject" name="id_subject" type="hidden" value="@TempData["id_subject"]" />
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                        @*chon chuyên đề*@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Tên chuyên đề</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7" style="padding-left: 0px;">

                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.id_thematic, null,
                                       new { @class = "form-control show-tick", data_live_search = "true" })

                                </div>
                                @Html.ValidationMessageFor(model => model.id_thematic, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        @*noi dung cau hỏi*@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Nội dung câu hỏi</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        @Html.TextAreaFor(model => model.question_content, new { @class = "form-control no-resize auto-growth", @placeholder = "Nhập nội dung câu hỏi", @required = "required", @autocomplete = "off" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.question_content, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Hình ảnh</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="file" name="file" id="file" />

                                    </div>
                                    <p style="margin-top: 3px; margin-left: 73px;"><strong>Ghi chú:</strong> Chỉ cho phép upload file<strong> ảnh</strong> và file đó phải có dung lượng dưới 3mb.</p>
                                </div>

                            </div>
                        </div>

                        @* đáp án A *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án A</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.A, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập đáp án A", @required = "required", @autocomplete = "off" } })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.A, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        @* đáp án B *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án B</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.B, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập đáp án B", @required = "required", @autocomplete = "off" } })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.B, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        @* đáp án C *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án C</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.C, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập đáp án C", @required = "required", @autocomplete = "off" } })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.C, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        @* đáp án D *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án D</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    <div class="form-line">
                                        @Html.EditorFor(model => model.D, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập đáp án D", @required = "required", @autocomplete = "off" } })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.D, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                        @* đáp án đúng *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án đúng</label>
                            </div>
                            <div class="col-sm-4" style="padding-left: 0px; padding-right: 0px;">
                                <div class="col-sm-10" style="padding-left: 0px;">

                                    @Html.DropDownList("correct_answer", new List<SelectListItem>
                           {
                               new SelectListItem{ Selected=true,Text = "A", Value = "A"},
                               new SelectListItem{ Text = "B", Value = "B"},
                               new SelectListItem{ Text = "C", Value = "C"},
                               new SelectListItem{ Text = "D", Value = "D"}

                           }, new { @class = "form-control show-tick" })
                                </div>
                                @Html.ValidationMessageFor(model => model.correct_answer, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @*thay đổi không *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đổi chỗ đáp án</label>
                            </div>
                            <div class="col-sm-4" style="padding-left: 0px; padding-right: 0px;">
                                <div class="col-sm-10" style="padding-left: 0px;">

                                    @Html.DropDownList("is_change", new List<SelectListItem>
                           {
                               new SelectListItem{ Selected=true,Text = "Có", Value = "1"},
                               new SelectListItem{ Text = "Không", Value = "0"}

                           }, new { @class = "form-control show-tick" })
                                </div>
                                @Html.ValidationMessageFor(model => model.is_change, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-sm-6">
                                <button type="submit" class="btn bg-orange waves-effect">
                                    <i class="material-icons">save</i>
                                    <span>Lưu</span>
                                </button>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-sm-6">

                            </div>
                        </div>
                    </div>
                }

            <div>

                <a href="/Admin/Subject/QDetail/@TempData["id_subject"]" class="btn bg-light-blue waves-effect"><i class="material-icons">navigate_before</i><span>Trở về</span></a>
                <a href="/Admin/Subject/AddQuest/@TempData["id_subject"]" class="btn btn-info waves-effect"><i class="material-icons">file_upload</i><span>Tải lên tệp câu hỏi</span></a>
                <a href="/Admin/Subject/QEssayCreate/@TempData["id_subject"]" class="btn btn-info waves-effect"><i class="material-icons">add_box</i><span>Thêm câu hỏi tự luận</span></a>

            </div>
            </div>
            <!--#BODY-->
        </div>
    </div>
</div>

<!-- #END# ADD FORM -->
<!-- Jquery Core Js -->
<script src="/Assets/admin/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="/Assets/admin/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="/Assets/admin/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="/Assets/admin/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="/Assets/admin/plugins/node-waves/waves.js"></script>
<!-- Autosize Plugin Js -->
<script src="/Assets/admin/plugins/autosize/autosize.js"></script>
<!-- Moment Plugin Js -->
<script src="/Assets/admin/plugins/momentjs/moment.js"></script>
<!-- Bootstrap Notify Plugin Js -->
<script src="/Assets/admin/plugins/bootstrap-notify/bootstrap-notify.js"></script>

<!-- Custom Js -->
<script src="/Assets/admin/js/admin.js"></script>
<script src="/Assets/admin/js/pages/forms/basic-form-elements.js"></script>
@if (TempData["NoticeMessage"] != null)
{


    <script>
    $.notify({

        title: '<strong>Thông báo: </strong> ',
        message: '@TempData["NoticeMessage"]'
    }, {
        type: '@TempData["NoticeType"]',
        delay: 3000,
        template: '<div data-notify="container" class="col-xs-11 col-sm-2 alert alert-{0}" role="alert">' +
            '<span data-notify="title">{1}</span>' +
            '<span data-notify="message">{2}</span>' +
        '</div>'
    });
    </script>

}

<!-- Demo Js -->
<script src="/Assets/admin/js/demo.js"></script>

DoAn_ThiTracNghiem_Complete/Areas/Admin/Views/Subject/QEssayCreate.cshtml
@model Model.EF.Question


@{
    ViewBag.Title = "Thêm ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section css
    {

    <!-- Wait Me Css -->
    <link href="/Assets/admin/plugins/waitme/waitMe.css" rel="stylesheet" />
    <!-- Bootstrap Select Css -->
    <link href="/Assets/admin/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="/Assets/admin/css/style.css" rel="stylesheet">

}
@section title
{
    <title>Thêm câu hỏi cho môn @TempData["subject_name"]</title>
}

<div class="block-header">

</div>
<!-- ADD FORM -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    THÊM CÂU HỎI CHO MÔN @TempData["subject_name"].ToString().ToUpper()
                </h2>
            </div>
            <div class="body">
                @using (Html.BeginForm("QCreate", "Subject", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <input data-val="true" id="id_subject" name="id_subject" type="hidden" value="@TempData["id_subject"]" />
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                        @*chon chuyên đề*@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Tên chuyên đề</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7" style="padding-left: 0px;">

                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.id_thematic, null,
                                       new { @class = "form-control show-tick", data_live_search = "true" })

                                </div>
                                @Html.ValidationMessageFor(model => model.id_thematic, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        @*noi dung cau hỏi*@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Nội dung câu hỏi</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    @if (ViewBag.Error == 1)
                                    {
                                        <div class="alert alert-danger">
                                            Đã có lỗi xảy ra.
                                        </div>
                                    }
                                    else if (ViewBag.Error == -1)
                                    {
                                        <div class="alert alert-success">
                                            Lưu thành công.
                                        </div>
                                    }
                                    <textarea id="ckeditor" name="question_content">
                                      
                                    </textarea>


                                </div>
                            </div>
                        </div>
                        @*img*@
                        <input data-val="true" id="file" name="file" type="hidden" value="" />
                        @* đáp án A *@
                        <div class="row clearfix">
                            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                <label>Đáp án</label>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-7">
                                <div class="form-group">
                                    @Html.ValidationMessageFor(model => model.A, "", new { @class = "text-danger" })
                                    @Html.TextAreaFor(model => model.A,  new { @class = "form-control", @required = "required", @autocomplete = "off", @id = "ckeditor1"   }  )
                                </div>
                            </div>
                        </div>
                        @* đáp án B *@
                        <input data-val="true" id="B" name="B" type="hidden" value="-1" />
                        @* đáp án C *@
                        <input data-val="true" id="C" name="C" type="hidden" value="-1" />
                        @* đáp án D *@
                        <input data-val="true" id="D" name="D" type="hidden" value="-1" />
                        @* đáp án đúng *@
                        <input data-val="true" id="correct_answer" name="correct_answer" type="hidden" value="-1" />
                        @*thay đổi không *@
                        <input data-val="true" id="is_change" name="is_change" type="hidden" value="0" />
                        <div class="row clearfix">
                            <div class="col-sm-6">

                            </div>
                        </div>
                    </div>
                }

                <div>

                    <a href="/Admin/Subject/QDetail/@TempData["id_subject"]" class="btn bg-light-blue waves-effect"><i class="material-icons">navigate_before</i><span>Trở về</span></a>
                    <a href="/Admin/Subject/AddQuest/@TempData["id_subject"]" class="btn btn-info waves-effect"><i class="material-icons">file_upload</i><span>Tải lên tệp câu hỏi</span></a>

                </div>
            </div>
            <!--#BODY-->
        </div>
    </div>
</div>

<!-- #END# ADD FORM -->
<!-- Jquery Core Js -->
<script src="/Assets/admin/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap Core Js -->
<script src="/Assets/admin/plugins/bootstrap/js/bootstrap.js"></script>
<!-- Select Plugin Js -->
<script src="/Assets/admin/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<!-- Slimscroll Plugin Js -->
<script src="/Assets/admin/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- Waves Effect Plugin Js -->
<script src="/Assets/admin/plugins/node-waves/waves.js"></script>
<!-- Autosize Plugin Js -->
<script src="/Assets/admin/plugins/autosize/autosize.js"></script>
<!-- Moment Plugin Js -->
<script src="/Assets/admin/plugins/momentjs/moment.js"></script>
<!-- Bootstrap Notify Plugin Js -->
<script src="/Assets/admin/plugins/bootstrap-notify/bootstrap-notify.js"></script>

<!-- Custom Js -->
<!-- <script src="~/Assets/admin/js/pages/QEssayCreate.js"></script> -->
<script src="/Assets/admin/js/admin.js"></script>

@if (TempData["NoticeMessage"] != null)
{


    <script>
    $.notify({

        title: '<strong>Thông báo: </strong> ',
        message: '@TempData["NoticeMessage"]'
    }, {
        type: '@TempData["NoticeType"]',
        delay: 3000,
        template: '<div data-notify="container" class="col-xs-11 col-sm-2 alert alert-{0}" role="alert">' +
            '<span data-notify="title">{1}</span>' +
            '<span data-notify="message">{2}</span>' +
        '</div>'
    });
    </script>

}
<script src="~/Assets/admin/plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML"></script>

<script>
    //CKEditor
    CKEDITOR.replace('ckeditor', {
        htmlEncodeOutput: true
    });
    CKEDITOR.config.height = 300;
    CKEDITOR.config.extraPlugins = 'mathjax';
    CKEDITOR.config.mathJaxLib = '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML';
</script>

<script>
    //CKEditor
    CKEDITOR.replace('ckeditor1', {
        htmlEncodeOutput: true
    });
    CKEDITOR.config.height = 300;
    CKEDITOR.config.extraPlugins = 'mathjax';
    CKEDITOR.config.mathJaxLib = '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML';
</script>

<!-- Demo Js -->
<script src="/Assets/admin/js/demo.js"></script>